---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: local-bluecray-info
  namespace: default
spec:
  secretName: local-bluecray-info-staging-tls
  issuerRef:
    name: letsencrypt-staging
    kind: ClusterIssuer
  commonName: "*.local.bluecray.info"
  dnsNames:
  - "local.bluecray.info"
  - "*.local.bluecray.info"
